### PR TITLE
Ebourne GitHub automation 3

### PR DESCRIPTION
**Pull request by EmilyBourne**
Testing github automation in a fork

### CODE REVIEW

**Comment by EmilyBourne** [comment]
@pyccel/pyccel-dev please request changes so I can test this mechanism

**Review by yguclu — CHANGES_REQUESTED** [review]
I think you should really use US English spelling!

**Review by yguclu — CHANGES_REQUESTED** [review]
The instructions are too polite!

**Review by yguclu — APPROVED** [review]
Great job! 🙌

**Review by aihya — CHANGES_REQUESTED** [review]
Request change test

**Comment by EmilyBourne** [comment]
Hopefully that fixes the missing values in the text. Can someone request changes once more then everyone approve please

**Review by aihya — CHANGES_REQUESTED** [review]
Test 2

**Comment by EmilyBourne** [comment]
@aihya format in the wrong place. Test 3?

**Review by aihya — CHANGES_REQUESTED** [review]
Test 3

**Comment by EmilyBourne** [comment]
@aihya please can you approve and see if the label changes (we will do a proper review on the pyccel repo)

**Review by aihya — APPROVED** [review]

**Pull request closed without merging**
