### PR TITLE
Ebourne bot fixes

### PR DESCRIPTION
**Pull request by EmilyBourne**

### CODE REVIEW

**Comment by yguclu** [comment]
/bot run pickle editable_pickle pickle_wheel linux_anaconda windows_anaconda

**Comment by yguclu** [comment]
/bot run pickle editable_pickle pickle_wheel linux_anaconda windows_anaconda

**Comment by yguclu** [comment]
@EmilyBourne There seems to be an error in the interaction with the bot. I cannot run the tests.

**Comment by EmilyBourne** [comment]
@yguclu I'm not sure it's possible to run more than one test at a time with the `/bot run` command. I should add this functionality or at least raise an error

**Comment by EmilyBourne** [comment]
@yguclu never mind, it worked in the main repo using spaces so I don't think that was the problem. I think it's just because you aren't approved for this repo. I have added a message so it should explain if you ask to run tests. Can you try again and then I will tell it to trust you.

Also the bot works comment by comment not line by line so it is not possible to put multiple commands in the same commit

**Comment by yguclu** [comment]
> @@yguclu It looks like the Pyccel maintainers trust you 🚀. I will now start running tests when you request them.

Aren't there too many `@` here?

**Comment by yguclu** [comment]
/bot run pickle editable_pickle pickle_wheel linux_anaconda windows_anaconda

**Comment by EmilyBourne** [comment]
> /bot run pickle editable_pickle pickle_wheel linux_anaconda windows_anaconda

Yes but it's because I used the wrong command. That's why I sent a second version just after

**Comment by EmilyBourne** [comment]
test

**Comment by EmilyBourne** [comment]
test

**Pull request closed without merging**
